### PR TITLE
Allow user to provide Guzzle options in requests

### PR DESCRIPTION
**Pull request by chapa**
Related to #292

### CODE REVIEW

**Comment by chapa** [comment]
Arf, just realized it could be better to name the option `requestOptions` instead of `guzzle` (like I suggested in #292) to be consistent with `OpenStack::__construct()`.
What do you think @haphan ?

**Comment by giulioprovasi** [comment]
hey, any eta on this ? have same issue and is kinda blocking the usage of this package for me :/

**Comment by haphan** [comment]
> Arf, just realized it could be better to name the option `requestOptions` instead of `guzzle` (like I suggested in #292) to be consistent with `OpenStack::__construct()`.
> What do you think @haphan ?

Thanks @chapa. I think it makes a lot of sense to re-use the key `requestOptions`. Can you help to update the PR? 

I'm also thinking to have an integration test case to cover this new feature. I can help with integration test if you don't have time.

**Comment by chapa** [comment]
Hey, I'm on vacation right now but I'll take a look when I get back.

If you can do an integration test it would be great !

**Comment by chapa** [comment]
Just pushed the commit to rename `"guzzle'` to `'requestOptions'`.

I'm sorry but I don't have the time to dig into integration tests, I didn't even manage to run them because of this error :
```
$ php ./tests/integration/run.php -s=ObjectStore
INFO: =================================================
INFO: Starting objectstore v1 core integration test(s)
INFO: =================================================
PHP Fatal error:  Uncaught RuntimeException: OpenStack\Integration\Objectstore\v1\CoreTest does not exist in [...]/tests/integration/Runner.php:115
[...]
```
Looks like an autoloading problem, but composer.json seems fine and the autoload.php is required in run.php so I don't understand, I didn't look any further

**Comment by haphan** [comment]
Cool. I will run integration tests on my end.

**Pull request merged**
