### PR TITLE
Adding missing `jsonKey` on patchPolicy() method

### PR DESCRIPTION
**Pull request by samuel4x4**
We need this in order to validate and update a Policy object.

### CODE REVIEW

**Comment by samuel4x4** [comment]
@jamiehannaford is there an issue in the building process?

**Comment by samuel4x4** [comment]
Hi @haphan, do you think the validation process for this PR can be restarted from your side? I think it was a temporary connectivity issue on the building process that may not appear again on a new try. I'm using Policy PATCH on my project and I would appreciate a review and merge for this PR. Thanks a lot!

**Comment by haphan** [comment]
@samuel4x4 Please rebase with `master` and push again. This issue has been fixed in master due to recent upgrade of travis ci

**Comment by samuel4x4** [comment]
@haphan I'm not sure I did is properly, using the we UI.. If it's not alright this way, I can close this one and create a new PR starting from the updated php-opencloud/openstack:master brench.

**Comment by haphan** [comment]
@samuel4x4 Yeah can create new PR from `master`

**Comment by samuel4x4** [comment]
A new clean PR will replace this one. Thanks @haphan

**Comment by samuel4x4** [comment]
#185

**Pull request closed without merging**
