### PR TITLE
[rfr] Merge php-opencloud/common

### PR DESCRIPTION
**Pull request by haphan**
https://github.com/php-opencloud/openstack/pull/64

### CODE REVIEW

**Comment by haphan** [comment]
@jamiehannaford  shall we also refactor namespace from `OpenCloud` to `OpenStack`?

**Comment by jamiehannaford** [comment]
@haphan Yeah I think that's best if we do

**Comment by haphan** [comment]
@jamiehannaford Any comments?

**Comment by jamiehannaford** [comment]
Awesome work @haphan 🚀

**Pull request merged**
