### PR TITLE
Allow postService() method to set description property

### PR DESCRIPTION
**Pull request by samuel4x4**
You cannot set `description` for a new service right now, I see the patchService() method have it, so I added it also for the creation.

### CODE REVIEW

**Comment by samuel4x4** [comment]
@haphan

**Comment by haphan** [comment]
thank you @samuel4x4 🚀

**Comment by samuel4x4** [comment]
Thank you @haphan ;) New release please? :)

**Comment by haphan** [comment]
I will probably merge 1 or 2 PRs to `master` within this week then I will tag a new release. 😺

**Comment by samuel4x4** [comment]
Thanks a lot for your good work on providing this very helpful SDK ;)

**Comment by samuel4x4** [comment]
@haphan Check please PR #123, I hope you'll tag a new release now ;) Thanks ;)

**Pull request merged**
