### PR TITLE
[WIP] Application credentials

### PR DESCRIPTION
**Pull request by smarcet**
this feature branch adds the 

application credentials to identity api

depicted here 

https://docs.openstack.org/keystone/latest/user/application_credentials.html

### CODE REVIEW

**Comment by smarcet** [comment]
guys greetings i work for the OSF i do think this feature will be really useful matter of fact we are using this lib to integration openstackid.org with swift object storage using app credentials

regards

**Comment by haphan** [comment]
Hi Sebastian, thanks foe your work. I will review this PR as soon as I can

**Comment by haphan** [comment]
I think it would be very useful for this SDK to support application credentials (added since Openstack 3.10 Queen). 

Having said that, we probably want to do it in a systematic way; meaning to cover (1) the [Application credential API](https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=authenticating-with-an-application-credential-detail#application-credentials) as well as (2) the login flow.

@smarcet  Are you able to work on it?

**Comment by smarcet** [comment]
@haphan as far i understand
PR covers (2) [login flow]
i do think that (1) could be covered on a second PR
regards

**Comment by drzraf** [comment]
I'm all for getting this merged too, but one concern I have is when instantiating `OpenStack\OpenStack` with such an array of options (as expected by the current prototype): 
```yaml
# actually Symfony D-I
authUrl: '%openstack.authurl%'
region: '%openstack.region%'
debugLog: true
user:
    name: '%openstack.username%'
    password: '%openstack.password%'
    domain:
        id: 'default'
scope:
    project:
        id: '%openstack.tenantId%'
logger: '@monolog.logger'
```

and it sounds like such a prototype **does not allow for application credentials** (or am I overlooking something?)

**Comment by drzraf** [comment]
@smarcet

**Comment by martijnve** [comment]
We have tested this MR in our application and would very much like this to be in the mainline. Is there anything we can do to assist in this feature getting merged?

**Comment by k0ka** [comment]
Superseded by https://github.com/php-opencloud/openstack/pull/380
Released in https://github.com/php-opencloud/openstack/releases/tag/v3.5.0

**Pull request closed without merging**
