### PR TITLE
Add fault property to Server

### PR DESCRIPTION
**Pull request by casperboone**
This PR adds a fault property to the `Server` model for asynchronous errors.

### CODE REVIEW

**Comment by jamiehannaford** [comment]
So looking at the docs, it seems like a sample response would be this:

```json
{
  "server": {
    "fault": {
      "code" : 500,
      "created": "2010-08-10T11:59:59Z",
      "message": "No valid host was found. There are not enough hosts available.",
      "details": "..."
    }
}
```

if we return as an array, we're effectively handing over a blob of unstructured data to the user with no guaranteed contract. I'm wondering whether it's worth making a new Fault model to wrap these fields (and also converting `created` to a Datetime object)? This might be overkill though.

@haphan What do you think?

**Comment by haphan** [comment]
It looks like `fault` structure is used in many scenarios as described [here](https://developer.openstack.org/api-guide/compute/faults.html), I think we should wrap it as a model @jamiehannaford

**Comment by casperboone** [comment]
@jamiehannaford @haphan I've created a `Fault` model. It's extending `AbstractResource` which is not entirely fitting, but I think it's the easiest way to let the model have the behavior it needs.

**Comment by jamiehannaford** [comment]
You'll need to rebase to get the travis.yml fix

**Comment by casperboone** [comment]
@jamiehannaford Done! :)

**Comment by haphan** [comment]
@casperboone  🚀

**Pull request merged**
