### PR TITLE
Added sample in openstack docs for creating an object

### PR DESCRIPTION
**Pull request by karnajani**

### CODE REVIEW

**Comment by jamiehannaford** [comment]
@karnajani Thanks! :rocket:

**Comment by karnajani** [comment]
@jamiehannaford what's the difference between this repo and https://github.com/rackspace/php-opencloud?

They are obviously different, just trying to make sure I use the right one for a production app

**Comment by jamiehannaford** [comment]
@karnajani https://github.com/rackspace/php-opencloud is the old v1 library that will be deprecated. This repo is the new redesigned v2, which should be the new official SDK once things are stabilised. This repo has all of the Core OpenStack services, so my feeling is that it can be used in production.

**Comment by karnajani** [comment]
thanks @jamiehannaford 

I appreciate the help :)

**Pull request merged**
