### PR TITLE
PHP 7.2 Compatibility (+ updated php-cs-fixer & PHPUnit)

### PR DESCRIPTION
**Pull request by mrwogu**

### CODE REVIEW

**Comment by mrwogu** [comment]
Build was passed successfully for:
* 5.0
* 5.1

but i don't know why for 5.2 i've got php-cs-fixer sugesstions on files which i didn't touch.

**Comment by haphan** [comment]
I think we definitely should update some out-of-date dependencies like `php-cs-fixer`.  Don't mind if you can update php-cs-fixer in this PR as well.

Support for `php 7.2` will result in a new major version since there are some BC breaks.

**Comment by haphan** [comment]
@mrwogu `BaseObject` sounds misleading to me, at least from a developers perspective, `BaseObject` often use in the context of an abstract class.

What about using StorageObject instead?

**Comment by mrwogu** [comment]
Ok, i've renamed from `Object` to `StorageObject`.
php-cs-fixer has been updated and works fine now.

Unfortunately, PHPUnit is also outdated and I had to update it to a new version.
Could you check these errors?

**Comment by mrwogu** [comment]
@haphan could you check Travis and rebuild my currently PR?
`Failed to clone the git@github.com:php-opencloud/Sami.git repository, try running in interactive mode so that you can enter your GitHub credentials`

**Comment by mrwogu** [comment]
Current status (PHP 7.2)
zrzut ekranu 2018-01-06 o 17 10 12

**Comment by mrwogu** [comment]
@haphan could you merge this into php-opencloud:php-7.2?
I also rebased my branch with master.

**Comment by haphan** [comment]
Great works @mrwogu but I think commits got messed up during rebase. 

Can you try to rebase it again?

**Comment by mrwogu** [comment]
@haphan done

**Comment by haphan** [comment]
@mrwogu Awesome works! 🎸 

I've made only minor improvements to the README  and `php-cs-fixer`.

Branch `2.0` will now contain version 2.x and `master` for 3.x.

**Pull request merged**
