### PR TITLE
[rfr] Issue 103 port fixed ips

### PR DESCRIPTION
**Pull request by haphan**
Waiting for integration test

### CODE REVIEW

**Comment by haphan** [comment]
@flakjacket95 Can you can checkout this branch and test if it works as expected or not? thanks

**Comment by flakjacket95** [comment]
Works fine for me, so yep, thanks!

**Comment by haphan** [comment]
Integration test added and passed

```
haphan@hpbook:~/Projects/openstack$ php ./tests/integration/run.php -s networking
INFO: =================================================
INFO: Starting networking v2 core integration test(s)
INFO: =================================================
INFO: (1.02s) Created network 80f61da8-7b60-443a-b473-723fb2bb9a47
INFO: (0.71s) Deleted network 80f61da8-7b60-443a-b473-723fb2bb9a47
INFO: (0.00s) Created network 9ff7560c-afa4-4d55-a5e2-76d612f507bc
INFO: (0.72s) Deleted network 9ff7560c-afa4-4d55-a5e2-76d612f507bc
INFO: (0.51s) Created network 9ff7560c-afa4-4d55-a5e2-76d612f507bc
INFO: (0.72s) Updated network ff5dd816-f7f3-4546-ade5-59fb025d0e1f to use this name: phptest_rBpwt
INFO: (0.74s) Retrieved the details of network ff5dd816-f7f3-4546-ade5-59fb025d0e1f
INFO: (0.69s) Deleted network ff5dd816-f7f3-4546-ade5-59fb025d0e1f
INFO: (1.43s) Created subnet 5178c59c-4709-43da-bed7-fcb961e98eda
INFO: (1.02s) Deleted subnet 5178c59c-4709-43da-bed7-fcb961e98eda
INFO: (0.00s) Created subnet f03e7dff-eb8d-4165-a7ed-783bc9ac94e3
INFO: (0.51s) Deleted subnet f03e7dff-eb8d-4165-a7ed-783bc9ac94e3
INFO: (2.67s) Created subnet ee2e4b52-38df-4b3c-bbc0-5b8fb5b73d72 with host routes
INFO: (3.07s) Created subnet 1eec1dbf-3cc8-439d-88be-e7d3f905ded7
INFO: (0.70s) Updated subnet 1eec1dbf-3cc8-439d-88be-e7d3f905ded7 to use this name: phptest_wKDPp
INFO: (0.53s) Retrieved the details of subnet 1eec1dbf-3cc8-439d-88be-e7d3f905ded7
INFO: (1.11s) Deleted subnet 1eec1dbf-3cc8-439d-88be-e7d3f905ded7
INFO: (0.84s) Deleted network a28e6869-ea31-4435-8cf4-7d8ad8190d51
INFO: (0.00s) Test port
INFO: (5.63s) Test port with fixed IP
INFO: (0.61s) Created network cef7ce5e-9ffe-4ad1-8fb4-76b107a05897
INFO: (0.61s) Created subnet a1cfd7fc-4d27-4379-ae0e-192bd0ea91df
INFO: (1.13s) Created port 5d15281e-bca5-4d58-bb2e-09a65cbf8708
INFO: (0.73s) Deleted port 5d15281e-bca5-4d58-bb2e-09a65cbf8708
INFO: (1.05s) Deleted subnet a1cfd7fc-4d27-4379-ae0e-192bd0ea91df
INFO: (0.74s) Deleted network cef7ce5e-9ffe-4ad1-8fb4-76b107a05897
INFO: Finished all tests! Time taken: 27.50s.
INFO: ===========
INFO: Cleaning up
INFO: ===========
INFO: =================================================
INFO: Starting networking v2 core integration test(s)
INFO: =================================================
INFO: (0.00s) Creating external network
INFO: (0.62s) Creating subnet for external network f893de74-7552-4e80-97cb-b4fe733f0903
INFO: (0.85s) Creating internal network
INFO: (0.75s) Creating subnet for internal network d772a117-f049-4cf8-a2a1-f7180cade7a0
INFO: (0.79s) Creating router for external network f893de74-7552-4e80-97cb-b4fe733f0903
INFO: (1.53s) Create interface for subnet 51bdaed1-3682-46eb-abe9-b2f46803cf44 and router 13145ad7-33c1-42f4-bd39-fdfac638506e
INFO: (1.23s) Creating port for internal network d772a117-f049-4cf8-a2a1-f7180cade7a0
INFO: (0.77s) Create floating IP
INFO: (1.05s) List floating IPs
INFO: (0.89s) Get floating IP
INFO: (0.26s) Update floating IP
INFO: (2.04s) Delete floating IP
INFO: Finished all tests! Time taken: 16.75s.
INFO: ===========
INFO: Cleaning up
INFO: ===========
INFO: =================================================
INFO: Starting networking v2 core integration test(s)
INFO: =================================================
INFO: ===========
INFO: Cleaning up
INFO: ===========
```

**Comment by haphan** [comment]
Would you be able to review and merge this PR @jamiehannaford? thanks

**Comment by jamiehannaford** [comment]
👍

**Pull request merged**
